# @baseUrl = http://localhost:7071
@baseUrl = https://ccd-func-otpo3ptm46ydu.azurewebsites.net


### Start a new image set job (returns jobId)
POST {{baseUrl}}/api/StartImageSet
Content-Type: application/json

{}
